/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.swiperefreshlayout;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040028;
        public static final int font = 0x7f0400da;
        public static final int fontProviderAuthority = 0x7f0400dc;
        public static final int fontProviderCerts = 0x7f0400dd;
        public static final int fontProviderFetchStrategy = 0x7f0400de;
        public static final int fontProviderFetchTimeout = 0x7f0400df;
        public static final int fontProviderPackage = 0x7f0400e0;
        public static final int fontProviderQuery = 0x7f0400e1;
        public static final int fontStyle = 0x7f0400e2;
        public static final int fontVariationSettings = 0x7f0400e3;
        public static final int fontWeight = 0x7f0400e4;
        public static final int ttcIndex = 0x7f040215;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f06006b;
        public static final int notification_icon_bg_color = 0x7f06006c;
        public static final int ripple_material_light = 0x7f060077;
        public static final int secondary_text_default_material_light = 0x7f060079;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070050;
        public static final int compat_button_inset_vertical_material = 0x7f070051;
        public static final int compat_button_padding_horizontal_material = 0x7f070052;
        public static final int compat_button_padding_vertical_material = 0x7f070053;
        public static final int compat_control_corner_material = 0x7f070054;
        public static final int compat_notification_large_icon_max_height = 0x7f070055;
        public static final int compat_notification_large_icon_max_width = 0x7f070056;
        public static final int notification_action_icon_size = 0x7f0700c6;
        public